### ISSUE TITLE
AttributeError: module 'pcl' has no attribute 'PointCloud'

### ISSUE THREAD

**Issue by MahdiKhSh** [biter0088/pc-nerf#1]
Hello and thanks for sharing the source code of your article
Please guide me to fix this problem. I use Ubuntu 20.4 and Python 3.8.
I get this error when I run the following command.
bash ./shells/pretraining/KITTI00_originalnerf_train.bash
![Screenshot from 2024-04-29 18-24-20](https://github.com/biter0088/pc-nerf/assets/109808524/bea7a5a7-edad-47a0-a95c-5c0498119d2d)

**Comment by biter0088** [comment]
I apologize for just seeing your question. I have written a solution to this problem on a Chinese blog site. Let's see if it helps in your case. The link is [here](https://blog.csdn.net/BIT_HXZ/article/details/128675662). Good luck to you.

**Comment by biter0088** [comment]
The python-pcl library needs to be installed, its official github link is [here](https://github.com/strawlab/python-pcl).
