### ISSUE TITLE
Question :  as claimed , how did you obtained the point cloud for the whole trip ?

### ISSUE THREAD

**Issue by git-sachin1066** [biter0088/pc-nerf#2]
which tool you use to create the point cloud of the whole trip??

**Comment by biter0088** [comment]
> which tool you use to create the point cloud of the whole trip??

Our proposed PC-NeRF model was evaluated using 13 point cloud data sequences from **two publicly available outdoor datasets, namely the MaiCity and KITTI datasets**. For more details, please refer to Section IV-A of the paper. The point clouds in the **KITTI** dataset were **captured using a 64-line LiDAR sensor installed on a vehicle driving in real-world conditions.** LiDAR is a sensor similar to a camera that provides accurate distance measurements and generates point clouds directly without the need for special tools. The **MaiCity** dataset, on the other hand, **simulates the principle of data collection** by a vehicle-mounted LiDAR sensor in the real world by placing virtual LiDAR sensors in a virtual urban block environment, creating **synthetic point clouds** with precise pose information.

For further information on these two datasets, please refer to the following papers and websites:

Resources related to the KITTI dataset:
(1) "Vision meets Robotics: The KITTI Dataset"
(2) "Data Fusion in Infrastructure-Augmented Autonomous Driving Systems: Why? Where? and How?"
(3) [KITTI Dataset Website](https://www.cvlibs.net/datasets/kitti/)

Resources related to the MaiCity dataset:
(1) "Poisson Surface Reconstruction for LiDAR Odometry and Mapping"
(2) [MaiCity Dataset Website](https://www.ipb.uni-bonn.de/data/mai-city-dataset/index.html)

**Comment by git-sachin1066** [comment]
i misquoted my question, sorry for inconvenineces, 
LIDAR gives us point cloud for sure, my question more toward the scene splitting.
Are you deciding to splitting the scene in run time? or you created the the complete point cloud of the whole large scene in your first step and then do scene splitting?? if so which algorithm you used to  point cloud for the entire scene from raw point cloud

**Comment by biter0088** [comment]
> i misquoted my question, sorry for inconvenineces, LIDAR gives us point cloud for sure, my question more toward the scene splitting. Are you deciding to splitting the scene in run time? or you created the the complete point cloud of the whole large scene in your first step and then do scene splitting?? if so which algorithm you used to point cloud for the entire scene from raw point cloud

I'm splitting the scene at run time and building a small scene using a sequential multi-frame point cloud. But I think "create the the complete point cloud of the whole large scene in the first step and then do scene splitting" is a more efficient way to utilize the point cloud. You can try SLAM (with loopback detection) or other methods.
